
insert into centro_custo (descricao) values ('ACERTO DE CAIXA');
insert into centro_custo (descricao) values ('AGUA');
insert into centro_custo (descricao) values ('ALIMENTAÇÃO');
insert into centro_custo (descricao) values ('ALUGUEL');
insert into centro_custo (descricao) values ('CARRO');
insert into centro_custo (descricao) values ('CARTÃO');
insert into centro_custo (descricao) values ('COMUNICAÇÃO');
insert into centro_custo (descricao) values ('DEPOSITO');
insert into centro_custo (descricao) values ('DESCONTO');
insert into centro_custo (descricao) values ('DOAÇÃO');
insert into centro_custo (descricao) values ('EMPRESTIMO');
insert into centro_custo (descricao) values ('PRO-LABORE OLIVIR');
insert into centro_custo (descricao) values ('FUNCIONARIO');
insert into centro_custo (descricao) values ('INVESTIMENTOS E CONSORCIOS');
insert into centro_custo (descricao) values ('LIMPEZA');
insert into centro_custo (descricao) values ('LOCOMOÇÃO');
insert into centro_custo (descricao) values ('LUZ');
insert into centro_custo (descricao) values ('MATERIAL DE CONSUMO');
insert into centro_custo (descricao) values ('MOVEIS');
insert into centro_custo (descricao) values ('PADARIA E ALIMENTOS');
insert into centro_custo (descricao) values ('PESSOAL');
insert into centro_custo (descricao) values ('PRESTAÇÃO DA CASA');
insert into centro_custo (descricao) values ('ROUPAS E ACESSORIOS');
insert into centro_custo (descricao) values ('SAUDE');
insert into centro_custo (descricao) values ('SEGURANÇA');
insert into centro_custo (descricao) values ('TAXA');
insert into centro_custo (descricao) values ('TRANSFERENCIA');
insert into centro_custo (descricao) values ('WSOLUÇÃO');
insert into centro_custo (descricao) values ('MERCADO');
insert into centro_custo (descricao) values ('MANUTENÇÃO CARRO');
insert into centro_custo (descricao) values ('LOTERIAS');